### ISSUE TITLE
Same Path Error

### ISSUE THREAD

**Issue by usgdev** [ElecTreeFrying/drag-import-relative-path#6] opened 2023-07-19 04:01 UTC
When I tried to use extension  following error occurred.
 
![error](https://github.com/ElecTreeFrying/drag-import-relative-path/assets/50322386/b7355e90-26c6-4a58-ab12-b0455ad270eb)

**Comment by ElecTreeFrying** [comment] 2023-07-22 02:48
Hello, I'm linking my comment from another closed issue. Could you please confirm if the solution I provided solves your issue?

https://github.com/ElecTreeFrying/drag-import-relative-path/issues/4#issuecomment-1483869115

> Thank you for raising this concern. I understand your point, but based on the accompanying .gif, it appears that the behavior is intended and not a bug. To successfully drag a file, please ensure that the file is selected in the tree view as shown in the .gif. If you have any further questions or issues, feel free to ask.
> 
> If there are no further replies within a week, we will close this issue, assuming it's resolved. Thank you.

![227730846-b468a93a-c53b-4f39-91fb-e5d72f9274f4](https://github.com/ElecTreeFrying/drag-import-relative-path/assets/19801459/823c9442-2d8a-4ebf-9d46-09669b5900f3)

**Comment by HansKans** [comment] 2023-07-26 11:35
Hi, i have the same problem. But i cannot select the files(left click) from the tree-view because they are directly opened...
How can this extension been used anyway?

Best regards

**Comment by ElecTreeFrying** [comment] 2023-08-09 15:04
Closing this issue as a duplicate of [#4](https://github.com/ElecTreeFrying/drag-import-relative-path/issues/4). Please refer to the original discussion for further comments and updates. Thanks

**Closed as completed by ElecTreeFrying** 2023-08-09 15:04 UTC
