### ISSUE TITLE
Same file path.

### ISSUE THREAD

**Issue by bio-informatician** [ElecTreeFrying/drag-import-relative-path#4] opened 2023-01-27 13:39 UTC
I installed this extension, but for importing the assets always get "Same file path." error. The file I want to import is located within the same parent folder but different subfolder.

**Comment by daugaard47** [comment] 2023-03-03 15:29
same issue

**Comment by Fadlo31** [comment] 2023-03-04 14:42
same here while using module.css with next.js

**Comment by ElecTreeFrying** [comment] 2023-03-25 16:54
Thank you for raising this concern. I understand your point, but based on the accompanying .gif, it appears that the behavior is intended and not a bug. To successfully drag a file, please ensure that the file is selected in the tree view as shown in the .gif. If you have any further questions or issues, feel free to ask.

If there are no further replies within a week, we will close this issue, assuming it's resolved. Thank you.

![ddddddddddddd](https://user-images.githubusercontent.com/19801459/227730846-b468a93a-c53b-4f39-91fb-e5d72f9274f4.gif)

**Comment by elidiazgt** [comment] 2023-03-31 03:50
But if you select the file in the tree view, the file open. It happens every time.

**Comment by ctf0** [comment] 2023-05-13 22:12
@ElecTreeFrying i have the same issue and i dont know how the ext suppose to work, i have a one click to open file so maybe thats the issue ? but atm there is no way to use the extension features 😢

**Comment by HansKans** [comment] 2023-08-21 12:02
Hi, i have the same problem. I cannot select any file from another folder.
How can this extension been used anyway?

Best regards

**Comment by ElecTreeFrying** [comment] 2023-08-26 19:49
Hello everyone, I apologize for my lack of responsiveness regarding this particular issue. I wanted to inform you that the issue has been identified and resolved. I have released an update to fix it. Kindly update the extension, and then reload or restart the VSCode editor to ensure the changes take effect. Thank you for your understanding.

**Closed as completed** 2023-08-30 03:34 UTC
Labels: bug

**Comment by HansKans** [comment] 2023-09-04 08:35
Thanks alot! Works perfect for me now!
